### ISSUE TITLE
Support relative path on remote URLs

### ISSUE THREAD

**Issue by alexandremcosta** [kim-company/kim_hls#8]
If a master playlist with HTTP urls contains relative paths, it cannot find the media playlists
```
22:35:45.768 [error] GenServer #PID<0.1329.0> terminating
** (MatchError) no match of right hand side value: {:error, {:no_scheme}}
    (kim_hls 0.1.0) lib/hls/playlist/media/tracker.ex:56: HLS.Playlist.Media.Tracker.read_media_playlist/2
    (kim_hls 0.1.0) lib/hls/playlist/media/tracker.ex:62: HLS.Playlist.Media.Tracker.handle_refresh/2
```

I'm researching the code, but if you can give me a clue on where to fix that, it would save us a lot of time.

**Comment by dmorn** [comment]
Hi @alexandremcosta! Could you please provide some more context? In the meanwhile:
* If you're using kim_hls on a local file, you should use the [OS](https://github.com/kim-company/kim_hls/blob/main/lib/hls/fs/reader/os.ex) FS implementation.
* tracker can only be used with alternative renditions
* to obtain the proper media url, you should use the [build_media_uri](https://github.com/kim-company/kim_hls/blob/d010dc7a1b12c5d2727c607468e9fc8895a9d169/lib/hls/playlist/master.ex#L46C7-L46C22) function, which takes care of building the correct URI

Let me know how it goes. At some point it might be useful to make an `examples` directory I guess, if there is interest on the library

**Comment by alexandremcosta** [comment]
Ok, I will work on an example from `kim_hls`

**Comment by alexandremcosta** [comment]
Actually, my bad. I didn't understood who to use the lib correctly. [build_media_uri](https://github.com/kim-company/kim_hls/blob/d010dc7a1b12c5d2727c607468e9fc8895a9d169/lib/hls/playlist/master.ex#L46C7-L46C22) perfectly solves my problem.
